𝗢𝗿𝗱𝗶𝗻𝗮𝗹 𝗻𝘂𝗺𝗯𝗲𝗿𝗶𝗻𝗴 𝗲𝗻𝗰𝗼𝗱𝗶𝗻𝗴 𝗼𝗿 𝗟𝗮𝗯𝗲𝗹 𝗘𝗻𝗰𝗼𝗱𝗶𝗻𝗴

Ordinal categorical variables

Ordinal data is a categorical, statistical data type where the variables have natural, ordered categories and the distances between the categories is not known.

For example:

1. Student's grade in an exam (A, B, C or Fail).
2. Educational level, with the categories: Elementary school, High school, College graduate, PhD ranked from 1 to 4.

When the categorical variables are ordinal, the most straightforward best approach is to replace the labels by some ordinal number based on the ranks.

In [2]:
import pandas as pd 
import datetime

In [11]:
# Create a variable with dates, and from that extract the weekday
# I create a list of dates with 20 days difference from today
# and then transform it into a datetime

df_base=datetime.datetime.today()
df_date_list=[df_base - datetime.timedelta(days=x) for x in range(0,20)]
df=pd.DataFrame(df_date_list)
df.columns=['days']
df

                         days
0  2026-03-07 18:59:10.724077
1  2026-03-06 18:59:10.724077
2  2026-03-05 18:59:10.724077
3  2026-03-04 18:59:10.724077
4  2026-03-03 18:59:10.724077
5  2026-03-02 18:59:10.724077
6  2026-03-01 18:59:10.724077
7  2026-02-28 18:59:10.724077
8  2026-02-27 18:59:10.724077
9  2026-02-26 18:59:10.724077
10 2026-02-25 18:59:10.724077
11 2026-02-24 18:59:10.724077
12 2026-02-23 18:59:10.724077
13 2026-02-22 18:59:10.724077
14 2026-02-21 18:59:10.724077
15 2026-02-20 18:59:10.724077
16 2026-02-19 18:59:10.724077
17 2026-02-18 18:59:10.724077
18 2026-02-17 18:59:10.724077
19 2026-02-16 18:59:10.724077

In [20]:
# extract the week day name

df['day_of_week']=df['days'].dt.day_name()
df.head(6)

                        days day_of_week
0 2026-03-07 18:59:10.724077    Saturday
1 2026-03-06 18:59:10.724077      Friday
2 2026-03-05 18:59:10.724077    Thursday
3 2026-03-04 18:59:10.724077   Wednesday
4 2026-03-03 18:59:10.724077     Tuesday
5 2026-03-02 18:59:10.724077      Monday

In [24]:
# Engineer categorical variable by ordinal number replacement

weekday_map = {'Monday':1,
               'Tuesday':2,
               'Wednesday':3,
               'Thursday':4,
               'Friday':5,
               'Saturday':6,
               'Sunday':7
}

df['day_ordinal'] = df.day_of_week.map(weekday_map)
df.head(20)

                         days day_of_week  day_ordinal
0  2026-03-07 18:59:10.724077    Saturday            6
1  2026-03-06 18:59:10.724077      Friday            5
2  2026-03-05 18:59:10.724077    Thursday            4
3  2026-03-04 18:59:10.724077   Wednesday            3
4  2026-03-03 18:59:10.724077     Tuesday            2
5  2026-03-02 18:59:10.724077      Monday            1
6  2026-03-01 18:59:10.724077      Sunday            7
7  2026-02-28 18:59:10.724077    Saturday            6
8  2026-02-27 18:59:10.724077      Friday            5
9  2026-02-26 18:59:10.724077    Thursday            4
10 2026-02-25 18:59:10.724077   Wednesday            3
11 2026-02-24 18:59:10.724077     Tuesday            2
12 2026-02-23 18:59:10.724077      Monday            1
13 2026-02-22 18:59:10.724077      Sunday            7
14 2026-02-21 18:59:10.724077    Saturday            6
15 2026-02-20 18:59:10.724077      Friday            5
16 2026-02-19 18:59:10.724077    Thursday            4
17 2026-02-18 18:59:10.724077   Wednesday            3
18 2026-02-17 18:59:10.724077     Tuesday            2
19 2026-02-16 18:59:10.724077      Monday            1

𝗢𝗿𝗱𝗶𝗻𝗮𝗹 𝗠𝗲𝗮𝘀𝘂𝗿𝗲𝗺𝗲𝗻𝘁 𝗔𝗱𝘃𝗮𝗻𝘁𝗮𝗴𝗲𝘀

Ordinal measurement is normally used for surveys and questionnaires. Statistical analysis is applied to the responses once they are collected to place the people who took the survey into the various categories. The data is then compared to draw inferences and conclusions about the whole surveyed population with regard to the specific variables. The advantage of using ordinal measurement is ease of collation and categorization. If you ask a survey question without providing the variables, the answers are likely to be so diverse they cannot be converted to statistics.

With Respect to Machine Learning

1. Keeps the semantical information of the variable (human readable content)
2. Straightforward

𝗢𝗿𝗱𝗶𝗻𝗮𝗹 𝗠𝗲𝗮𝘀𝘂𝗿𝗲𝗺𝗲𝗻𝘁 𝗗𝗶𝘀𝗮𝗱𝘃𝗮𝗻𝘁𝗮𝗴𝗲𝘀

The same characteristics of ordinal measurement that create its advantages also create certain disadvantages. The responses are often so narrow in relation to the question that they create or magnify bias that is not factored into the survey. For example, on the question about satisfaction with the governor, people might be satisfied with his job performance but upset about a recent sex scandal. The survey question might lead respondents to state their dissatisfaction about the scandal, in spite of satisfaction with his job performance -- but the statistical conclusion will not differentiate.

With Respect to Machine Learning

Does not add machine learning valuable information